export const TOGGLE_EMPLOYEE_LOADER = 'TOGGLE_EMPLOYEE_LOADER';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const TOGGLE_EMPLOYEES_COLLAPSED = 'TOGGLE_EMPLOYEES_COLLAPSED';